name: Run-Tests

on:
   push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: Collection/Petstore.postman_collection.json
          envVar: '[{ "key": "API_Key", "value": "${{secrets.API_KEY}}" }]'
